### PR TITLE
Fix Contract PDF Generation

### PR DESCRIPTION
**Pull request by Katee**
Fixes https://github.com/FireflyArtsCollective/ffagc/issues/51

Does not included improved tests.

### CODE REVIEW

**Comment by ywwg** [comment]
thanks for looking at this!  I am still getting an error when I log in as an artist and try to generate the contract:

Started POST "/grant_submissions/1/generate_contract.pdf" for 127.0.0.1 at 2017-11-30 13:59:32 -0500
Processing by GrantSubmissionsController#generate_contract as PDF
  Parameters: {"authenticity_token"=>"AmPUsz4gOa/1fQG008cPBhOUXHgLAfeBj3MgO9PiUKxQssYX676Lm1oWc1nqJup7Ojhirl9qQN/3ew16S812NA==", "id"=>"1"}
  GrantSubmission Load (0.1ms)  SELECT  "grant_submissions".* FROM "grant_submissions" WHERE "grant_submissions"."id" = ? LIMIT 1  [["id", 1]]
  Artist Load (0.1ms)  SELECT  "artists".* FROM "artists" WHERE "artists"."id" = ? LIMIT 1  [["id", 1]]
  Admin Exists (0.1ms)  SELECT  1 AS one FROM "admins" LIMIT 1
   (0.1ms)  SELECT "grant_submissions".id FROM "grant_submissions" WHERE "grant_submissions"."artist_id" = ?  [["artist_id", 1]]
  CACHE (0.0ms)  SELECT  "grant_submissions".* FROM "grant_submissions" WHERE "grant_submissions"."id" = ? LIMIT 1  [["id", "1"]]
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.5ms)

ActionView::MissingTemplate (Missing template errors/503 with {:locale=>[:en], :formats=>[:pdf], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in:
  * "/home/owen/src/github/ffagc/app/views"
):
  app/controllers/application_controller.rb:131:in `deny_access'


I wonder if this is a configuration issue on my end, but the error is not making it clear what the issue is

**Comment by Katee** [comment]
Good call. I've updated the logic to remove the separate call of `authorize! can :read, @grant_submission`. Now it is only protected by the `generate_contract` ability, which activated artists have.

If you still have trouble make sure the Artist you are using is `activated`. The logic for which artists can generate a contract is here: https://github.com/FireflyArtsCollective/ffagc/blob/efb419a8f99b3d8bba4c7ad1d0b7c0f8bed264bc/app/models/ability.rb#L39-L40

You can activated an Artist in the rails console with `Artist.find(id).activate!`.

Ignore the failing specs, I haven't finished setting up Circleci.

**Comment by ywwg** [comment]
ok progress, the contract now generates, but the output pdf is blank.  

template_dir in grant_contract.rb should now be File.join(Rails.root, 'lib', 'contract_templates') because that folder moved, and when I uncomment the begin/rescue bit in initialize() I get:

undefined local variable or method `template_dir'

not sure why it's not seeing the template_dir func at the bottom of the file

**Comment by ywwg** [comment]
(specifically the line filename = File.join(template_dir, "#{@grant.downcase}.tmpl.erb"))

**Comment by Katee** [comment]
I'm so sorry, I've been touching this between other tasks and haven't done a good job of actually testing.

I think with these changes it now works. I tested generating the 'bex' template.

**Comment by ywwg** [comment]
no worries, I would have been more surprised if there had been zero regressions after such a large amount of changes.  The amount of improvement to the UI is still worth the small number of easily fixed issues we've found so far.

this works now, thanks!

**Pull request merged**
